### ISSUE TITLE
There is not cluster.yml for lesson 6

### ISSUE THREAD

**Issue by leokury** [udacity/nd064-c3-microservices-security-exercises#1]
I didn't file the cluster.yml for lesson 6.

**Comment by ericcgu** [comment]
https://github.com/udacity/nd064-c3-microservices-security-exercises/tree/master/lesson-6-runtime-monitoring-and-incident-response/exercises/starter

**Comment by ericcgu** [comment]
@revaniki two repos for one workshop makes it confusing.

**Comment by walidshaari** [comment]
I still do not see the cluster.yaml, anything wrong with using the 2 rke nodes from before?

**Comment by abhiojha8** [comment]
The one node cluster YAML file can be found here - https://github.com/udacity/nd064-c3-microservices-security-project-starter/blob/master/starter/cluster.yml
