### ISSUE TITLE
deprecated prometheus is not working

### ISSUE THREAD

**Issue by ericcgu** [udacity/nd064-c3-microservices-security-exercises#4]
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm repo add stable https://kubernetes-charts.storage.googleapis.com # this is deprecated
helm repo add stable https://charts.helm.sh/stable
helm repo update
helm install prometheus prometheus-community/kube-prometheus-stack

**Comment by abhiojha8** [comment]
Pinned this issue for visibility. Thanks for the suggestion!

**Comment by marcindulak** [comment]
Should the issue rather be closed after the course materials are updated to remove the references to https://charts.helm.sh/stable?

**Comment by SudKul** [comment]
Hi @marcindulak 
Can you check the previous course _Observability >> Lesson 2 Observability Tools >> Exercise: Installing Prometheus and Grafana_ page?
Udacity has updated the instructions in the classroom. 

Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
